"""empty message

Revision ID: f563520ca1fb
Revises: c01ce817a86e
Create Date: 2024-04-25 11:32:39.783846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f563520ca1fb'
down_revision = 'c01ce817a86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_type_associations',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['restaurant_types.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_type_associations')
    op.drop_table('restaurant_types')
    # ### end Alembic commands ###
